/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.potromon.iu;

import com.mycompany.potromon.entidades.Genero;
import com.mycompany.potromon.entidades.Potromon;

/**
 *
 * @author darkheaven
 */
public class InfoPotromon extends javax.swing.JFrame {

    Potromon potromon;
    
    /**
     * Creates new form InfoPotromon
     */
    public InfoPotromon(java.awt.Frame parent, boolean modal, Potromon potromon) {
    
    initComponents();
    
    if (potromon != null) {
    this.potromon = potromon;
    lblNombre.setText("Nombre: " + potromon.getNombre());
    lblApodo.setText("Apodo: " + potromon.getApodo());

    Genero generoObj = Genero.getGeneroById(potromon.getIdGenero());
    String genero = (generoObj != null) ? generoObj.getGenero() : "Desconocido";
    lblGenero.setText("Genero: " + genero);

    lblTipo.setText("Tipo: " + potromon.getTipo());
    lblAltura.setText("Altura: " + String.valueOf(potromon.getAltura()));
    lblPeso.setText("Peso: " + String.valueOf(potromon.getPeso()));
    lblCiudad.setText("Ciudad: " + potromon.getCiudad());
    lblEntrenador.setText("Entrenador: " + potromon.getEntrenador());
    lblHabilidadPrincipal.setText("Habilidad Principal: " + potromon.getHabilidadPrincipal());
    lblHabilidadSecundaria.setText("Habilidad Secundaria: " + potromon.getHabilidadSecundaria());
    lblPuntajeCombate.setText("Puntaje de Combate: " + String.valueOf(potromon.getPuntajeBatalla()));
    lblDescripcion.setText(potromon.getDescripcion());
}
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        lblApodo = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        lblHabilidadPrincipal = new javax.swing.JLabel();
        lblHabilidadSecundaria = new javax.swing.JLabel();
        lblTituloDescripcion = new javax.swing.JLabel();
        lblEntrenador = new javax.swing.JLabel();
        lblPuntajeCombate = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        lblNombre.setText("Nombre:");

        lblApodo.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        lblApodo.setText("Apodo:");

        lblGenero.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        lblGenero.setText("Genero:");

        lblTipo.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        lblTipo.setText("Tipo:");

        lblAltura.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        lblAltura.setText("Altura:");

        lblPeso.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        lblPeso.setText("Peso:");

        lblCiudad.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        lblCiudad.setText("Ciudad:");

        lblHabilidadPrincipal.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        lblHabilidadPrincipal.setText("Habilidad Principal:");

        lblHabilidadSecundaria.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        lblHabilidadSecundaria.setText("Habilidad Secundaria:");

        lblTituloDescripcion.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        lblTituloDescripcion.setText("Descripcion:");

        lblEntrenador.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        lblEntrenador.setText("Entrenador:");

        lblPuntajeCombate.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        lblPuntajeCombate.setText("Puntaje de Combate:");

        lblDescripcion.setFont(new java.awt.Font("Liberation Sans", 2, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblApodo)
                            .addComponent(lblGenero)
                            .addComponent(lblTituloDescripcion)
                            .addComponent(lblTipo)
                            .addComponent(lblAltura)
                            .addComponent(lblPeso)
                            .addComponent(lblCiudad))
                        .addGap(298, 298, 298)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEntrenador)
                                .addComponent(lblHabilidadPrincipal)
                                .addComponent(lblHabilidadSecundaria))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPuntajeCombate)
                                .addGap(11, 11, 11))))
                    .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblApodo)
                        .addGap(18, 18, 18)
                        .addComponent(lblGenero)
                        .addGap(18, 18, 18)
                        .addComponent(lblTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAltura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCiudad)
                        .addGap(18, 18, 18)
                        .addComponent(lblTituloDescripcion))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblEntrenador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHabilidadPrincipal)
                        .addGap(16, 16, 16)
                        .addComponent(lblHabilidadSecundaria)
                        .addGap(169, 169, 169)
                        .addComponent(lblPuntajeCombate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        // Crear valores ficticios para pruebas
        java.awt.Frame parent = null; 
        boolean modal = false;
        Potromon potromon = new Potromon(); // Asegúrate de tener un constructor en Potromon

        // Crear la instancia
        InfoPotromon infoFrame = new InfoPotromon(parent, modal, potromon);
        infoFrame.setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblApodo;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEntrenador;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblHabilidadPrincipal;
    private javax.swing.JLabel lblHabilidadSecundaria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblPuntajeCombate;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTituloDescripcion;
    // End of variables declaration//GEN-END:variables
}
